title : Mark Goldman Portfolio
tagline: Site Tagline
author :
  name : Mark Goldman
  email : markgoldman@mit.edu
  github : goldmanm
  linkedin : www.linkedin.com/in/mjgoldman # this probably needs to be configured somewhere


markdown: kramdown
#highlighter: rb-pygments
permalink: /blog/:year/:month/:title.html
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "notes.md"]

rdiscount:
  extensions:
    - footnotes
    - autolink
    - smart

navigation:
 - text: thoughts
   url: /
 - text: about
   url: /about/
 - text: tools
   url: /toolbox.html

sass:
  sass_dir: _sass
  style: :expanded
  # nested
  # expanded
  # compact
  # compressed
