title : Jan Zheng Portfolio
tagline: Site Tagline
author :
  name : Jan Zheng
  email : contact@janzheng.com
  github : janzheng
  twitter : janistanian
  linkedin : www.linkedin.com/in/janzh # this probably needs to be configured somewhere


markdown: rdiscount
highlighter: pygments
permalink: /blog/:year/:month/:title.html
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "notes.txt"]


navigation:
 - text: thoughts
   url: /
 - text: about
   url: /about.html
 - text: tools
   url: /toolbox.html

sass:
  sass_dir: _sass
  style: :expanded
  # nested
  # expanded
  # compact
  # compressed
